[package]
name = "coldbrew"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
colored = "3.0.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
toml_edit = "0.23.2"
